export const lightTheme = {
  black: "#000000",
  text: "#333",
  whiteText: "#BDBDBD",
  backgroundColorTwo: "#FBFBFB",
  bigNumber: "#F2F2F2",
  background: "#FFF",
  backgroundForm: "#F3F3F3",
  footer: "#2C2C2C",
  footerText: "#FFF",
  hover: "#989898",
  backgroundSmallButton: "#F9F9F9",
  BigButtonBlack: "#333",
  BigButtonLight: "#FFF",
  BigButtonTextLight: "#FFF",
  BigButtonTextBlack: "#333",
  buttonTheme: "#FFF",
  ButtonColorTheme: "#787878",
  moon: "#F4A460",
  white: "#FFF",
};

export const darkTheme = {
  black: "#ffffff",
  text: "#DCDCDC",
  background: "#808080",
  bigNumber: "#D3D3D3",
  backgroundSmallButton: "#C0C0C0",
  footerText: "#DCDCDC",
  footer: "#2C2C2C",
  BigButtonBlack: "#333",
  BigButtonLight: "#FFF",
  BigButtonTextLight: "#DCDCDC",
  BigButtonTextBlack: "#333",
  backgroundColorTwo: "#696969",
  buttonTheme: "#A9A9A9",
  ButtonColorTheme: "#333",
  moon: "#FFFF00",
  white: "#FFF",
  hover: "#989898",
};
